packaging_format = 2

id = "mollysocket"
name = "mollysocket"
description.en = "Get signal notifications via UnifiedPush. "

version = "1.0~ynh1"

maintainers = ["marc0x1"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/MollySocket/mollysocket"
fund = "https://liberapay.com/S1m/"

[integration]
yunohost = ">= 11.1.6"
architectures = ['amd64']
multi_instance = true
ldap = "not_relevant" 
sso = "not_relevant"
# TODO: check real usage
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mollysocket"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.account_id]
    ask.en = "Account ID"
    help.en = "Settings > Notification > Push Strategy > Click on enabled > Copy the account ID"
    type = "string"

[resources]
    [resources.system_user]

    [resources.install_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8000