#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1
mollysocket_setup_source

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring systemd service..." --weight=1

ynh_script_progression --message="Starting systemd service..." --weight=1
ynh_systemd_action --action=start

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app

ynh_script_progression --message="Adding a command wrapper..." --weight=1
ynh_add_config -t "ms.sh" -d "$install_dir/ms.sh"
chown $app:$app "$install_dir/ms.sh"
chmod u+x "$install_dir/ms.sh"

ynh_script_progression --message="Configuring web server..." --weight=2
ynh_add_nginx_config

ynh_script_progression --message="Installation completed" --last