#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Checking version..." --weight=1
upgrade_type=$(ynh_check_app_version_changed)

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=6
	mollysocket_setup_source
fi

ynh_script_progression --message="Updating configuration file..." --weight=1
ynh_add_config -t "server.yml" -d "$install_dir/server.yml"

ynh_script_progression --message="Upgrading systemd configuration..." --weight=1
ynh_add_systemd_config

ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app

ynh_script_progression --message="Updating simple command wrapper..." --weight=1
ynh_add_config -t "ms.sh" -d "$install_dir/ms.sh"
chown $app:$app "$install_dir/ms.sh"
chmod u+x "$install_dir/ms.sh"

ynh_script_progression --message="Upgrading web server configuration..." --weight=2
ynh_add_nginx_config

ynh_script_progression --message="Restarting systemd service..." --weight=1
ynh_systemd_action --action=restart

ynh_script_progression --message="Upgrade completed" --last
